/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XBurgerMenu: typeof import('./src/@core/components/XBurgerMenu.vue')['default']
    XButton: typeof import('./src/@core/components/XButton.vue')['default']
    XDrawerBuilder: typeof import('./src/@core/components/XDrawerBuilder.vue')['default']
    XSwitchMode: typeof import('./src/@core/components/XSwitchMode.vue')['default']
  }
}
